####
GET http://localhost:5050/api/v1/chats/chat/26?profileId=84

####
GET http://localhost:5050/api/v1/chats/chat/25

###
POST http://localhost:5050/api/v1/chats/chat/message/save
Content-Type: application/json

{


  "chat_id": 29,
  "textMessage": "cxvgearg  nbcn"

}

###
GET http://localhost:5050/api/v1/chats/chat/messages/134?profileId=85&sizePage=15&numberPage=0

###
GET http://localhost:5050/api/v1/chats/chat/messages/19?sizePage=15&numberPage=0




###
GET http://localhost:5050/api/v1/chats/usersearch?search_request=деву&profileId=11

###
POST http://localhost:5050/api/v1/chats/add/86?profileId=12

###
POST http://localhost:5050/api/v1/chats/add/63

###
GET http://localhost:5050/api/v1/chats/chat/list?profileId=85

###
GET http://localhost:5050/api/v1/chats/chat/list

###
DELETE http://localhost:5050/api/v1/chats/del/86?profileId=12